# Generated by Django 4.2.1 on 2023-12-13 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(max_length=250)),
                ('desc', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=250)),
                ('ans', models.CharField(max_length=250)),
                ('options', models.CharField(max_length=1000)),
                ('lvl', models.IntegerField(default=1)),
                ('lang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercises.language')),
            ],
        ),
    ]
